repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/Lucas-C/pre-commit-hooks-lxml
    sha: v1.1.0
    hooks:
    -   id: forbid-html-img-without-alt-text
    -   id: detect-missing-css-classes
        args:
        - --css-files-dir
        - html/css
        - --html-files-dir
        - html/
    -   id: html-tags-blacklist
    -   id: html-attributes-blacklist
-   repo: https://github.com/Lucas-C/pre-commit-hooks-java
    sha: 1.3.10
    hooks:
    -   id: validate-html
        args: ["--ignore=has no cells beginning in it"]
